version: '3.8'

services:
  dash-app:
    build: .
    ports:
      - "8050:8050" # host:container
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
    command: python app_dash.py
    volumes:
      - .:/app
