sensores:
  micro_01:
    ubicacion_base: [4.609710, -74.081749]
    nombre_zona: "Zona Norte"
    sensores:
      sound_01:
        id: 1
        nombre: "Parque Central"
        offset: [2.0000, 1.0000]
      sound_02:
        id: 2
        nombre: "Centro Comercial"
        offset: [3.0010, -4.0010]
      
  
  micro_02:
    ubicacion_base: [4.599710, -74.091749]
    nombre_zona: "Zona Sur"
    sensores:
      sound_01:
        id: 4
        nombre: "Plaza Principal"
        offset: [0.0000, 0.0000]
      sound_02:
        id: 5
        nombre: "Hospital Regional"
        offset: [-0.0010, -0.0010]